name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install dependencies
        run: npm i

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: "npm"

      - name: Lint
        run: npx eslint "src/**/*.ts" "*.{js,cjs,mjs}"

      - name: Format check
        run: npx prettier --check "**/*.{ts,js,mjs,cjs,json,md}"

      - name: Type-check
        run: npm run test